/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddMediaPathRequest : Media Path dto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddMediaPathRequest {
    /// Gets or sets the name of the library.
    #[serde(rename = "Name")]
    pub name: String,
    /// Gets or sets the path to add.
    #[serde(rename = "Path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "PathInfo", skip_serializing_if = "Option::is_none")]
    pub path_info: Option<Box<crate::models::MediaPathDtoPathInfo>>,
}

impl AddMediaPathRequest {
    /// Media Path dto.
    pub fn new(name: String) -> AddMediaPathRequest {
        AddMediaPathRequest {
            name,
            path: None,
            path_info: None,
        }
    }
}


