/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddVirtualFolderRequest : Add virtual folder dto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddVirtualFolderRequest {
    #[serde(rename = "LibraryOptions", skip_serializing_if = "Option::is_none")]
    pub library_options: Option<Box<crate::models::AddVirtualFolderDtoLibraryOptions>>,
}

impl AddVirtualFolderRequest {
    /// Add virtual folder dto.
    pub fn new() -> AddVirtualFolderRequest {
        AddVirtualFolderRequest {
            library_options: None,
        }
    }
}


