/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdminNotificationDto : The admin notification dto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminNotificationDto {
    /// Gets or sets the notification name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the notification description.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Gets or sets the notification level.
    #[serde(rename = "NotificationLevel", skip_serializing_if = "Option::is_none")]
    pub notification_level: Option<Box<crate::models::NotificationLevel>>,
    /// Gets or sets the notification url.
    #[serde(rename = "Url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AdminNotificationDto {
    /// The admin notification dto.
    pub fn new() -> AdminNotificationDto {
        AdminNotificationDto {
            name: None,
            description: None,
            notification_level: None,
            url: None,
        }
    }
}


