/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ControlResponse {
    #[serde(rename = "Headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Xml", skip_serializing_if = "Option::is_none")]
    pub xml: Option<String>,
    #[serde(rename = "IsSuccessful", skip_serializing_if = "Option::is_none")]
    pub is_successful: Option<bool>,
}

impl ControlResponse {
    pub fn new() -> ControlResponse {
        ControlResponse {
            headers: None,
            xml: None,
            is_successful: None,
        }
    }
}


