/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreatePlaylistRequest : Create new playlist dto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePlaylistRequest {
    /// Gets or sets the name of the new playlist.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets item ids to add to the playlist.
    #[serde(rename = "Ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
    /// Gets or sets the user id.
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Gets or sets the media type.
    #[serde(rename = "MediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
}

impl CreatePlaylistRequest {
    /// Create new playlist dto.
    pub fn new() -> CreatePlaylistRequest {
        CreatePlaylistRequest {
            name: None,
            ids: None,
            user_id: None,
            media_type: None,
        }
    }
}


