/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DayPattern {
    #[serde(rename = "Daily")]
    Daily,
    #[serde(rename = "Weekdays")]
    Weekdays,
    #[serde(rename = "Weekends")]
    Weekends,

}

impl ToString for DayPattern {
    fn to_string(&self) -> String {
        match self {
            Self::Daily => String::from("Daily"),
            Self::Weekdays => String::from("Weekdays"),
            Self::Weekends => String::from("Weekends"),
        }
    }
}

impl Default for DayPattern {
    fn default() -> DayPattern {
        Self::Daily
    }
}




