/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GroupRepeatMode : Enum GroupRepeatMode.

/// Enum GroupRepeatMode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupRepeatMode {
    #[serde(rename = "RepeatOne")]
    RepeatOne,
    #[serde(rename = "RepeatAll")]
    RepeatAll,
    #[serde(rename = "RepeatNone")]
    RepeatNone,

}

impl ToString for GroupRepeatMode {
    fn to_string(&self) -> String {
        match self {
            Self::RepeatOne => String::from("RepeatOne"),
            Self::RepeatAll => String::from("RepeatAll"),
            Self::RepeatNone => String::from("RepeatNone"),
        }
    }
}

impl Default for GroupRepeatMode {
    fn default() -> GroupRepeatMode {
        Self::RepeatOne
    }
}




