/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IgnoreWaitRequestDto : Class IgnoreWaitRequestDto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IgnoreWaitRequestDto {
    /// Gets or sets a value indicating whether the client should be ignored.
    #[serde(rename = "IgnoreWait", skip_serializing_if = "Option::is_none")]
    pub ignore_wait: Option<bool>,
}

impl IgnoreWaitRequestDto {
    /// Class IgnoreWaitRequestDto.
    pub fn new() -> IgnoreWaitRequestDto {
        IgnoreWaitRequestDto {
            ignore_wait: None,
        }
    }
}


