/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageSavingConvention {
    #[serde(rename = "Legacy")]
    Legacy,
    #[serde(rename = "Compatible")]
    Compatible,

}

impl ToString for ImageSavingConvention {
    fn to_string(&self) -> String {
        match self {
            Self::Legacy => String::from("Legacy"),
            Self::Compatible => String::from("Compatible"),
        }
    }
}

impl Default for ImageSavingConvention {
    fn default() -> ImageSavingConvention {
        Self::Legacy
    }
}




