/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageOrientation {
    #[serde(rename = "TopLeft")]
    TopLeft,
    #[serde(rename = "TopRight")]
    TopRight,
    #[serde(rename = "BottomRight")]
    BottomRight,
    #[serde(rename = "BottomLeft")]
    BottomLeft,
    #[serde(rename = "LeftTop")]
    LeftTop,
    #[serde(rename = "RightTop")]
    RightTop,
    #[serde(rename = "RightBottom")]
    RightBottom,
    #[serde(rename = "LeftBottom")]
    LeftBottom,

}

impl ToString for ImageOrientation {
    fn to_string(&self) -> String {
        match self {
            Self::TopLeft => String::from("TopLeft"),
            Self::TopRight => String::from("TopRight"),
            Self::BottomRight => String::from("BottomRight"),
            Self::BottomLeft => String::from("BottomLeft"),
            Self::LeftTop => String::from("LeftTop"),
            Self::RightTop => String::from("RightTop"),
            Self::RightBottom => String::from("RightBottom"),
            Self::LeftBottom => String::from("LeftBottom"),
        }
    }
}

impl Default for ImageOrientation {
    fn default() -> ImageOrientation {
        Self::TopLeft
    }
}




