/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocationType : Enum LocationType.

/// Enum LocationType.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LocationType {
    #[serde(rename = "FileSystem")]
    FileSystem,
    #[serde(rename = "Remote")]
    Remote,
    #[serde(rename = "Virtual")]
    _Virtual,
    #[serde(rename = "Offline")]
    Offline,

}

impl ToString for LocationType {
    fn to_string(&self) -> String {
        match self {
            Self::FileSystem => String::from("FileSystem"),
            Self::Remote => String::from("Remote"),
            Self::_Virtual => String::from("Virtual"),
            Self::Offline => String::from("Offline"),
        }
    }
}

impl Default for LocationType {
    fn default() -> LocationType {
        Self::FileSystem
    }
}




