/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NextItemRequestDto : Class NextItemRequestDto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NextItemRequestDto {
    /// Gets or sets the playing item identifier.
    #[serde(rename = "PlaylistItemId", skip_serializing_if = "Option::is_none")]
    pub playlist_item_id: Option<String>,
}

impl NextItemRequestDto {
    /// Class NextItemRequestDto.
    pub fn new() -> NextItemRequestDto {
        NextItemRequestDto {
            playlist_item_id: None,
        }
    }
}


