/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NotificationDto : The notification DTO.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotificationDto {
    /// Gets or sets the notification ID. Defaults to an empty string.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Gets or sets the notification's user ID. Defaults to an empty string.
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Gets or sets the notification date.
    #[serde(rename = "Date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Gets or sets a value indicating whether the notification has been read. Defaults to false.
    #[serde(rename = "IsRead", skip_serializing_if = "Option::is_none")]
    pub is_read: Option<bool>,
    /// Gets or sets the notification's name. Defaults to an empty string.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the notification's description. Defaults to an empty string.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Gets or sets the notification's URL. Defaults to an empty string.
    #[serde(rename = "Url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Gets or sets the notification level.
    #[serde(rename = "Level", skip_serializing_if = "Option::is_none")]
    pub level: Option<Box<crate::models::NotificationLevel>>,
}

impl NotificationDto {
    /// The notification DTO.
    pub fn new() -> NotificationDto {
        NotificationDto {
            id: None,
            user_id: None,
            date: None,
            is_read: None,
            name: None,
            description: None,
            url: None,
            level: None,
        }
    }
}


