/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ParentalRating : Class ParentalRating.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParentalRating {
    /// Gets or sets the name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the value.
    #[serde(rename = "Value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
}

impl ParentalRating {
    /// Class ParentalRating.
    pub fn new() -> ParentalRating {
        ParentalRating {
            name: None,
            value: None,
        }
    }
}


