/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryFiltersLegacy {
    #[serde(rename = "Genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<String>>,
    #[serde(rename = "Tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "OfficialRatings", skip_serializing_if = "Option::is_none")]
    pub official_ratings: Option<Vec<String>>,
    #[serde(rename = "Years", skip_serializing_if = "Option::is_none")]
    pub years: Option<Vec<i32>>,
}

impl QueryFiltersLegacy {
    pub fn new() -> QueryFiltersLegacy {
        QueryFiltersLegacy {
            genres: None,
            tags: None,
            official_ratings: None,
            years: None,
        }
    }
}


