/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// QuickConnectDto : The quick connect request body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QuickConnectDto {
    /// Gets or sets the quick connect secret.
    #[serde(rename = "Secret")]
    pub secret: String,
}

impl QuickConnectDto {
    /// The quick connect request body.
    pub fn new(secret: String) -> QuickConnectDto {
        QuickConnectDto {
            secret,
        }
    }
}


