/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SendCommandType : Enum SendCommandType.

/// Enum SendCommandType.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SendCommandType {
    #[serde(rename = "Unpause")]
    Unpause,
    #[serde(rename = "Pause")]
    Pause,
    #[serde(rename = "Stop")]
    Stop,
    #[serde(rename = "Seek")]
    Seek,

}

impl ToString for SendCommandType {
    fn to_string(&self) -> String {
        match self {
            Self::Unpause => String::from("Unpause"),
            Self::Pause => String::from("Pause"),
            Self::Stop => String::from("Stop"),
            Self::Seek => String::from("Seek"),
        }
    }
}

impl Default for SendCommandType {
    fn default() -> SendCommandType {
        Self::Unpause
    }
}




