/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SessionUserInfo : Class SessionUserInfo.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SessionUserInfo {
    /// Gets or sets the user identifier.
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Gets or sets the name of the user.
    #[serde(rename = "UserName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SessionUserInfo {
    /// Class SessionUserInfo.
    pub fn new() -> SessionUserInfo {
        SessionUserInfo {
            user_id: None,
            user_name: None,
        }
    }
}


