/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StartupRemoteAccessDto : Startup remote access dto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StartupRemoteAccessDto {
    /// Gets or sets a value indicating whether enable remote access.
    #[serde(rename = "EnableRemoteAccess")]
    pub enable_remote_access: bool,
    /// Gets or sets a value indicating whether enable automatic port mapping.
    #[serde(rename = "EnableAutomaticPortMapping")]
    pub enable_automatic_port_mapping: bool,
}

impl StartupRemoteAccessDto {
    /// Startup remote access dto.
    pub fn new(enable_remote_access: bool, enable_automatic_port_mapping: bool) -> StartupRemoteAccessDto {
        StartupRemoteAccessDto {
            enable_remote_access,
            enable_automatic_port_mapping,
        }
    }
}


