/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SyncPlaySetPlaylistItemRequest : Class SetPlaylistItemRequestDto.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SyncPlaySetPlaylistItemRequest {
    /// Gets or sets the playlist identifier of the playing item.
    #[serde(rename = "PlaylistItemId", skip_serializing_if = "Option::is_none")]
    pub playlist_item_id: Option<String>,
}

impl SyncPlaySetPlaylistItemRequest {
    /// Class SetPlaylistItemRequestDto.
    pub fn new() -> SyncPlaySetPlaylistItemRequest {
        SyncPlaySetPlaylistItemRequest {
            playlist_item_id: None,
        }
    }
}


