/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TaskInfo : Class TaskInfo.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaskInfo {
    /// Gets or sets the name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the state of the task.
    #[serde(rename = "State", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<crate::models::TaskState>>,
    /// Gets or sets the progress.
    #[serde(rename = "CurrentProgressPercentage", skip_serializing_if = "Option::is_none")]
    pub current_progress_percentage: Option<f64>,
    /// Gets or sets the id.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "LastExecutionResult", skip_serializing_if = "Option::is_none")]
    pub last_execution_result: Option<Box<crate::models::TaskInfoLastExecutionResult>>,
    /// Gets or sets the triggers.
    #[serde(rename = "Triggers", skip_serializing_if = "Option::is_none")]
    pub triggers: Option<Vec<crate::models::TaskTriggerInfo>>,
    /// Gets or sets the description.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Gets or sets the category.
    #[serde(rename = "Category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Gets or sets a value indicating whether this instance is hidden.
    #[serde(rename = "IsHidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
    /// Gets or sets the key.
    #[serde(rename = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl TaskInfo {
    /// Class TaskInfo.
    pub fn new() -> TaskInfo {
        TaskInfo {
            name: None,
            state: None,
            current_progress_percentage: None,
            id: None,
            last_execution_result: None,
            triggers: None,
            description: None,
            category: None,
            is_hidden: None,
            key: None,
        }
    }
}


