/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TaskState : Enum TaskState.

/// Enum TaskState.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskState {
    #[serde(rename = "Idle")]
    Idle,
    #[serde(rename = "Cancelling")]
    Cancelling,
    #[serde(rename = "Running")]
    Running,

}

impl ToString for TaskState {
    fn to_string(&self) -> String {
        match self {
            Self::Idle => String::from("Idle"),
            Self::Cancelling => String::from("Cancelling"),
            Self::Running => String::from("Running"),
        }
    }
}

impl Default for TaskState {
    fn default() -> TaskState {
        Self::Idle
    }
}




