/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateStartupUserRequest : The startup user DTO.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateStartupUserRequest {
    /// Gets or sets the username.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the user's password.
    #[serde(rename = "Password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl UpdateStartupUserRequest {
    /// The startup user DTO.
    pub fn new() -> UpdateStartupUserRequest {
        UpdateStartupUserRequest {
            name: None,
            password: None,
        }
    }
}


