/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Video3DFormat {
    #[serde(rename = "HalfSideBySide")]
    HalfSideBySide,
    #[serde(rename = "FullSideBySide")]
    FullSideBySide,
    #[serde(rename = "FullTopAndBottom")]
    FullTopAndBottom,
    #[serde(rename = "HalfTopAndBottom")]
    HalfTopAndBottom,
    #[serde(rename = "MVC")]
    MVC,

}

impl ToString for Video3DFormat {
    fn to_string(&self) -> String {
        match self {
            Self::HalfSideBySide => String::from("HalfSideBySide"),
            Self::FullSideBySide => String::from("FullSideBySide"),
            Self::FullTopAndBottom => String::from("FullTopAndBottom"),
            Self::HalfTopAndBottom => String::from("HalfTopAndBottom"),
            Self::MVC => String::from("MVC"),
        }
    }
}

impl Default for Video3DFormat {
    fn default() -> Video3DFormat {
        Self::HalfSideBySide
    }
}




