/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VirtualFolderInfo : Used to hold information about a user's list of configured virtual folders.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualFolderInfo {
    /// Gets or sets the name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the locations.
    #[serde(rename = "Locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<String>>,
    /// Gets or sets the type of the collection.
    #[serde(rename = "CollectionType", skip_serializing_if = "Option::is_none")]
    pub collection_type: Option<Box<crate::models::CollectionTypeOptions>>,
    #[serde(rename = "LibraryOptions", skip_serializing_if = "Option::is_none")]
    pub library_options: Option<Box<crate::models::VirtualFolderInfoLibraryOptions>>,
    /// Gets or sets the item identifier.
    #[serde(rename = "ItemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    /// Gets or sets the primary image item identifier.
    #[serde(rename = "PrimaryImageItemId", skip_serializing_if = "Option::is_none")]
    pub primary_image_item_id: Option<String>,
    #[serde(rename = "RefreshProgress", skip_serializing_if = "Option::is_none")]
    pub refresh_progress: Option<f64>,
    #[serde(rename = "RefreshStatus", skip_serializing_if = "Option::is_none")]
    pub refresh_status: Option<String>,
}

impl VirtualFolderInfo {
    /// Used to hold information about a user's list of configured virtual folders.
    pub fn new() -> VirtualFolderInfo {
        VirtualFolderInfo {
            name: None,
            locations: None,
            collection_type: None,
            library_options: None,
            item_id: None,
            primary_image_item_id: None,
            refresh_progress: None,
            refresh_status: None,
        }
    }
}


