/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// XmlAttribute : Defines the MediaBrowser.Model.Dlna.XmlAttribute.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct XmlAttribute {
    /// Gets or sets the name of the attribute.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets or sets the value of the attribute.
    #[serde(rename = "Value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl XmlAttribute {
    /// Defines the MediaBrowser.Model.Dlna.XmlAttribute.
    pub fn new() -> XmlAttribute {
        XmlAttribute {
            name: None,
            value: None,
        }
    }
}


